# Form implementation generated from reading ui file 'DonHang/CTDH.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(878, 531)
        Form.setStyleSheet("background-color:rgb(248, 236, 240);")
        self.tb_CTDH = QtWidgets.QTableView(parent=Form)
        self.tb_CTDH.setGeometry(QtCore.QRect(40, 70, 801, 401))
        self.tb_CTDH.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tb_CTDH.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked)
        self.tb_CTDH.setAlternatingRowColors(True)
        self.tb_CTDH.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.tb_CTDH.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tb_CTDH.setObjectName("tb_CTDH")
        self.labelTitle = QtWidgets.QLabel(parent=Form)
        self.labelTitle.setGeometry(QtCore.QRect(220, 20, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitle.setStyleSheet(_translate("Form", "color: rgb(149, 106, 214);"))
        self.labelTitle.setText(_translate("Form", "CHI TIẾT ĐƠN HÀNG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
