# Form implementation generated from reading ui file 'DonHang/themCT.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 444)
        Form.setStyleSheet("background-color:rgb(248, 236, 240);")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(440, 160, 101, 21))
        self.label_6.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_6.setObjectName("label_6")
        self.txt_soluong = QtWidgets.QTextEdit(parent=Form)
        self.txt_soluong.setGeometry(QtCore.QRect(40, 190, 261, 41))
        self.txt_soluong.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_soluong.setObjectName("txt_soluong")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(390, 60, 191, 31))
        self.label.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label.setObjectName("label")
        self.cbo_tenSP = QtWidgets.QComboBox(parent=Form)
        self.cbo_tenSP.setGeometry(QtCore.QRect(350, 100, 261, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbo_tenSP.setFont(font)
        self.cbo_tenSP.setStyleSheet("QComboBox {\n"
"          background-color: white;\n"
"          border: 3px solid #3498db;  /* Viền xanh dương */\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }")
        self.cbo_tenSP.setObjectName("cbo_tenSP")
        self.btn_them = QtWidgets.QPushButton(parent=Form)
        self.btn_them.setGeometry(QtCore.QRect(250, 390, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_them.setFont(font)
        self.btn_them.setObjectName("btn_them")
        self.labelTitle = QtWidgets.QLabel(parent=Form)
        self.labelTitle.setGeometry(QtCore.QRect(100, 10, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(100, 150, 121, 31))
        self.label_2.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(80, 60, 211, 31))
        self.label_5.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_5.setObjectName("label_5")
        self.txt_maDH = QtWidgets.QTextEdit(parent=Form)
        self.txt_maDH.setGeometry(QtCore.QRect(40, 100, 261, 41))
        self.txt_maDH.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_maDH.setObjectName("txt_maDH")
        self.txt_dongia = QtWidgets.QTextEdit(parent=Form)
        self.txt_dongia.setGeometry(QtCore.QRect(350, 190, 261, 41))
        self.txt_dongia.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_dongia.setObjectName("txt_dongia")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(280, 250, 101, 21))
        self.label_7.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_7.setObjectName("label_7")
        self.txt_note = QtWidgets.QPlainTextEdit(parent=Form)
        self.txt_note.setGeometry(QtCore.QRect(120, 280, 411, 101))
        self.txt_note.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_note.setObjectName("txt_note")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "ĐƠN GIÁ"))
        self.label.setText(_translate("Form", "TÊN SẢN PHẨM"))
        self.btn_them.setStyleSheet(_translate("Form", "background-color: rgb(255, 255, 215); color: rgb(149, 106, 214); border-radius: 10px;"))
        self.btn_them.setText(_translate("Form", "THÊM"))
        self.labelTitle.setStyleSheet(_translate("Form", "color: rgb(149, 106, 214);"))
        self.labelTitle.setText(_translate("Form", "CHI TIẾT ĐƠN HÀNG MỚI"))
        self.label_2.setText(_translate("Form", "SỐ LƯỢNG"))
        self.label_5.setText(_translate("Form", "MÃ ĐƠN HÀNG"))
        self.label_7.setText(_translate("Form", "GHI CHÚ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
