# Form implementation generated from reading ui file 'DonHang/timKH.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background-color:rgb(248, 236, 240);")
        self.txt_maKH = QtWidgets.QTextEdit(parent=Form)
        self.txt_maKH.setGeometry(QtCore.QRect(70, 180, 261, 41))
        self.txt_maKH.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_maKH.setObjectName("txt_maKH")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(110, 140, 211, 31))
        self.label_5.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_5.setObjectName("label_5")
        self.labelTitle = QtWidgets.QLabel(parent=Form)
        self.labelTitle.setGeometry(QtCore.QRect(10, 10, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(110, 50, 211, 31))
        self.label_6.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_6.setObjectName("label_6")
        self.txt_tim = QtWidgets.QTextEdit(parent=Form)
        self.txt_tim.setGeometry(QtCore.QRect(70, 90, 261, 41))
        self.txt_tim.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_tim.setObjectName("txt_tim")
        self.btn_timKH = QtWidgets.QPushButton(parent=Form)
        self.btn_timKH.setGeometry(QtCore.QRect(110, 240, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_timKH.setFont(font)
        self.btn_timKH.setObjectName("btn_timKH")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "MÃ KHÁCH HÀNG"))
        self.labelTitle.setStyleSheet(_translate("Form", "color: rgb(149, 106, 214);"))
        self.labelTitle.setText(_translate("Form", "TÌM KHÁCH HÀNG"))
        self.label_6.setText(_translate("Form", "NHẬP SĐT / EMAIL"))
        self.btn_timKH.setStyleSheet(_translate("Form", "background-color: rgb(255, 255, 215); color: rgb(149, 106, 214); border-radius: 10px;"))
        self.btn_timKH.setText(_translate("Form", "TÌM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
