# Form implementation generated from reading ui file 'Donhang/themCT.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(906, 700)
        Form.setStyleSheet("background-color:rgb(248, 236, 240);")
        self.tb_CTDH = QtWidgets.QTableView(parent=Form)
        self.tb_CTDH.setGeometry(QtCore.QRect(50, 360, 811, 251))
        self.tb_CTDH.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tb_CTDH.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tb_CTDH.setAlternatingRowColors(True)
        self.tb_CTDH.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.tb_CTDH.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tb_CTDH.setObjectName("tb_CTDH")
        self.labelTitle = QtWidgets.QLabel(parent=Form)
        self.labelTitle.setGeometry(QtCore.QRect(220, 20, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("color: rgb(149, 106, 214);\n"
"font: 87 22pt \"Segoe UI Black\";")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.txt_note = QtWidgets.QPlainTextEdit(parent=Form)
        self.txt_note.setGeometry(QtCore.QRect(300, 260, 261, 41))
        self.txt_note.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_note.setObjectName("txt_note")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(100, 160, 81, 21))
        self.label_2.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(360, 80, 131, 31))
        self.label.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label.setObjectName("label")
        self.txt_maDH = QtWidgets.QTextEdit(parent=Form)
        self.txt_maDH.setGeometry(QtCore.QRect(20, 110, 261, 41))
        self.txt_maDH.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_maDH.setObjectName("txt_maDH")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(660, 80, 101, 21))
        self.label_6.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(400, 230, 71, 21))
        self.label_7.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_7.setObjectName("label_7")
        self.txt_soluong = QtWidgets.QTextEdit(parent=Form)
        self.txt_soluong.setGeometry(QtCore.QRect(20, 180, 261, 41))
        self.txt_soluong.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_soluong.setObjectName("txt_soluong")
        self.txt_dongia = QtWidgets.QTextEdit(parent=Form)
        self.txt_dongia.setGeometry(QtCore.QRect(580, 110, 261, 41))
        self.txt_dongia.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_dongia.setObjectName("txt_dongia")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(80, 80, 131, 21))
        self.label_5.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_5.setObjectName("label_5")
        self.btn_them = QtWidgets.QPushButton(parent=Form)
        self.btn_them.setGeometry(QtCore.QRect(350, 310, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_them.setFont(font)
        self.btn_them.setObjectName("btn_them")
        self.cbo_tenSP = QtWidgets.QComboBox(parent=Form)
        self.cbo_tenSP.setGeometry(QtCore.QRect(300, 110, 261, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbo_tenSP.setFont(font)
        self.cbo_tenSP.setStyleSheet("QComboBox {\n"
"          background-color: white;\n"
"          border: 3px solid #3498db;  /* Viền xanh dương */\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }")
        self.cbo_tenSP.setObjectName("cbo_tenSP")
        self.cbo_trangthai = QtWidgets.QComboBox(parent=Form)
        self.cbo_trangthai.setGeometry(QtCore.QRect(300, 180, 261, 41))
        self.cbo_trangthai.setStyleSheet("QComboBox {\n"
"          background-color: white;\n"
"          border: 3px solid #3498db;  /* Viền xanh dương */\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }")
        self.cbo_trangthai.setObjectName("cbo_trangthai")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(370, 160, 111, 21))
        self.label_8.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(650, 160, 111, 21))
        self.label_9.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_9.setObjectName("label_9")
        self.cbo_thanhtoan = QtWidgets.QComboBox(parent=Form)
        self.cbo_thanhtoan.setGeometry(QtCore.QRect(580, 180, 251, 41))
        self.cbo_thanhtoan.setStyleSheet("QComboBox {\n"
"          background-color: white;\n"
"          border: 3px solid #3498db;  /* Viền xanh dương */\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }")
        self.cbo_thanhtoan.setObjectName("cbo_thanhtoan")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(500, 630, 91, 31))
        self.label_3.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_3.setObjectName("label_3")
        self.txt_tongtien = QtWidgets.QTextEdit(parent=Form)
        self.txt_tongtien.setGeometry(QtCore.QRect(600, 620, 261, 41))
        self.txt_tongtien.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_tongtien.setObjectName("txt_tongtien")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitle.setText(_translate("Form", "CHI TIẾT ĐƠN HÀNG"))
        self.label_2.setText(_translate("Form", "SỐ LƯỢNG"))
        self.label.setText(_translate("Form", "TÊN SẢN PHẨM"))
        self.label_6.setText(_translate("Form", "ĐƠN GIÁ"))
        self.label_7.setText(_translate("Form", "GHI CHÚ"))
        self.label_5.setText(_translate("Form", "MÃ ĐƠN HÀNG"))
        self.btn_them.setStyleSheet(_translate("Form", "background-color: rgb(255, 255, 215); color: rgb(149, 106, 214); border-radius: 10px;"))
        self.btn_them.setText(_translate("Form", "THÊM"))
        self.label_8.setText(_translate("Form", "TRẠNG THÁI"))
        self.label_9.setText(_translate("Form", "THANH TOÁN"))
        self.label_3.setText(_translate("Form", "TỔNG TIỀN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
