# Form implementation generated from reading ui file 'Main/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UIMainWindow(object):
    def setupUi(self, UIMainWindow):
        UIMainWindow.setObjectName("UIMainWindow")
        UIMainWindow.resize(1204, 696)
        UIMainWindow.setStyleSheet("background-color: rgb(255, 255, 215);")
        self.centralwidget = QtWidgets.QWidget(parent=UIMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 600, 61, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Main\\../UI/hinhanh/user.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 75 30pt \"Segoe Script\";\n"
"")
        self.label_12.setObjectName("label_12")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(90, 80, 81, 81))
        self.widget_3.setStyleSheet("background-image: url(\"E:/HK6/DoAN/DoAn/hinhanh/logo2.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;  /* Ảnh sẽ tự động căn chỉnh để phủ toàn bộ */\n"
"\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 160, 271, 461))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_home = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_home.setFont(font)
        self.btn_home.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Main\\../hinhanh/8.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QtCore.QSize(20, 20))
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout.addWidget(self.btn_home)
        self.btn_spham = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_spham.setFont(font)
        self.btn_spham.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Main\\../hinhanh/11.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_spham.setIcon(icon1)
        self.btn_spham.setIconSize(QtCore.QSize(30, 30))
        self.btn_spham.setObjectName("btn_spham")
        self.verticalLayout.addWidget(self.btn_spham)
        self.btn_nhanvien = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_nhanvien.setFont(font)
        self.btn_nhanvien.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Main\\../hinhanh/4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nhanvien.setIcon(icon2)
        self.btn_nhanvien.setIconSize(QtCore.QSize(30, 30))
        self.btn_nhanvien.setObjectName("btn_nhanvien")
        self.verticalLayout.addWidget(self.btn_nhanvien)
        self.btn_donhang = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_donhang.setFont(font)
        self.btn_donhang.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Main\\../hinhanh/3.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_donhang.setIcon(icon3)
        self.btn_donhang.setIconSize(QtCore.QSize(30, 30))
        self.btn_donhang.setObjectName("btn_donhang")
        self.verticalLayout.addWidget(self.btn_donhang)
        self.btn_khachhang = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_khachhang.setFont(font)
        self.btn_khachhang.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Main\\../hinhanh/5.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_khachhang.setIcon(icon4)
        self.btn_khachhang.setIconSize(QtCore.QSize(30, 30))
        self.btn_khachhang.setObjectName("btn_khachhang")
        self.verticalLayout.addWidget(self.btn_khachhang)
        self.btn_nhacc = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_nhacc.setFont(font)
        self.btn_nhacc.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Main\\../hinhanh/6.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nhacc.setIcon(icon5)
        self.btn_nhacc.setIconSize(QtCore.QSize(25, 25))
        self.btn_nhacc.setObjectName("btn_nhacc")
        self.verticalLayout.addWidget(self.btn_nhacc)
        self.btn_logout = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Main\\../hinhanh/13.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_logout.setIcon(icon6)
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout.addWidget(self.btn_logout)
        self.Menu = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.Menu.setGeometry(QtCore.QRect(290, 20, 851, 621))
        self.Menu.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Menu.setStyleSheet("background-color:rgb(248, 236, 240);\n"
"\n"
"border-radius: 20px; /* Bo góc */;")
        self.Menu.setObjectName("Menu")
        self.trangchu = QtWidgets.QWidget()
        self.trangchu.setObjectName("trangchu")
        self.label_3 = QtWidgets.QLabel(parent=self.trangchu)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_3.setObjectName("label_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.trangchu)
        self.widget_2.setGeometry(QtCore.QRect(20, 60, 811, 141))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bill_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.bill_4.setStyleSheet("background-color: rgb(255, 253, 188);\n"
"color: rgb(255, 239, 178);\n"
"   border-radius: 20px; /* Bo góc */;")
        self.bill_4.setObjectName("bill_4")
        self.label_25 = QtWidgets.QLabel(parent=self.bill_4)
        self.label_25.setGeometry(QtCore.QRect(10, 0, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 87 12pt \"Arial\";\n"
"")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.bill_4)
        self.label_26.setGeometry(QtCore.QRect(200, 50, 41, 41))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("Main\\../hinhanh/9.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.lbl_dh = QtWidgets.QLabel(parent=self.bill_4)
        self.lbl_dh.setGeometry(QtCore.QRect(20, 60, 181, 31))
        self.lbl_dh.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 75 13pt \"Times New Roman\";")
        self.lbl_dh.setObjectName("lbl_dh")
        self.horizontalLayout_2.addWidget(self.bill_4)
        self.dthu_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.dthu_4.setStyleSheet("background-color: rgb(195, 255, 188);\n"
" border-radius: 20px; /* Bo góc */;")
        self.dthu_4.setObjectName("dthu_4")
        self.label_27 = QtWidgets.QLabel(parent=self.dthu_4)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 87 12pt \"Arial\";\n"
"\n"
"")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.dthu_4)
        self.label_28.setGeometry(QtCore.QRect(200, 50, 41, 41))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("Main\\../hinhanh/10.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.lbl_dt = QtWidgets.QLabel(parent=self.dthu_4)
        self.lbl_dt.setGeometry(QtCore.QRect(20, 60, 171, 31))
        self.lbl_dt.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 75 13pt \"Times New Roman\";")
        self.lbl_dt.setObjectName("lbl_dt")
        self.horizontalLayout_2.addWidget(self.dthu_4)
        self.spham_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.spham_4.setStyleSheet("background-color: rgb(255, 253, 188);\n"
"color: rgb(255, 239, 178);\n"
"   border-radius: 20px; /* Bo góc */;")
        self.spham_4.setObjectName("spham_4")
        self.label_29 = QtWidgets.QLabel(parent=self.spham_4)
        self.label_29.setGeometry(QtCore.QRect(190, 60, 51, 51))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("Main\\../hinhanh/11.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.spham_4)
        self.label_30.setGeometry(QtCore.QRect(10, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 87 12pt \"Arial\";\n"
"\n"
"")
        self.label_30.setObjectName("label_30")
        self.lbl_sp = QtWidgets.QLabel(parent=self.spham_4)
        self.lbl_sp.setGeometry(QtCore.QRect(20, 60, 101, 31))
        self.lbl_sp.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 75 13pt \"Times New Roman\";")
        self.lbl_sp.setObjectName("lbl_sp")
        self.horizontalLayout_2.addWidget(self.spham_4)
        self.Menu.addWidget(self.trangchu)
        self.sanpham = QtWidgets.QWidget()
        self.sanpham.setObjectName("sanpham")
        self.btn_suasp = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_suasp.setGeometry(QtCore.QRect(430, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_suasp.setFont(font)
        self.btn_suasp.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_suasp.setObjectName("btn_suasp")
        self.btn_xoasp = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_xoasp.setGeometry(QtCore.QRect(230, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoasp.setFont(font)
        self.btn_xoasp.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xoasp.setObjectName("btn_xoasp")
        self.cbo_sp = QtWidgets.QComboBox(parent=self.sanpham)
        self.cbo_sp.setGeometry(QtCore.QRect(20, 70, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cbo_sp.setFont(font)
        self.cbo_sp.setStyleSheet("QComboBox {\n"
"    \n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"font: 81 12pt \"Rockwell Extra Bold\";\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }\n"
"")
        self.cbo_sp.setObjectName("cbo_sp")
        self.cbo_sp.addItem("")
        self.cbo_sp.setItemText(0, "")
        self.cbo_sp.addItem("")
        self.cbo_sp.setItemText(1, "")
        self.btn_themsp = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_themsp.setGeometry(QtCore.QRect(40, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_themsp.setFont(font)
        self.btn_themsp.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_themsp.setObjectName("btn_themsp")
        self.label_10 = QtWidgets.QLabel(parent=self.sanpham)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_10.setObjectName("label_10")
        self.tb_sanpham = QtWidgets.QTableView(parent=self.sanpham)
        self.tb_sanpham.setGeometry(QtCore.QRect(30, 140, 791, 411))
        self.tb_sanpham.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tb_sanpham.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tb_sanpham.setAlternatingRowColors(True)
        self.tb_sanpham.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tb_sanpham.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tb_sanpham.setObjectName("tb_sanpham")
        self.txt_timkimsp = QtWidgets.QTextEdit(parent=self.sanpham)
        self.txt_timkimsp.setGeometry(QtCore.QRect(280, 70, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_timkimsp.setFont(font)
        self.txt_timkimsp.setStyleSheet("background-color: rgb(248, 236, 240);\n"
"border: 3px solid #ffffff;  /* Viền màu hồng */\n"
"        border-radius: 20px;\n"
"        padding: 5px 10px;")
        self.txt_timkimsp.setObjectName("txt_timkimsp")
        self.btn_timkiemsp = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_timkiemsp.setGeometry(QtCore.QRect(690, 80, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_timkiemsp.setFont(font)
        self.btn_timkiemsp.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_timkiemsp.setObjectName("btn_timkiemsp")
        self.btn_refresh = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_refresh.setGeometry(QtCore.QRect(640, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_refresh.setFont(font)
        self.btn_refresh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_refresh.setObjectName("btn_refresh")
        self.Menu.addWidget(self.sanpham)
        self.nhanvien = QtWidgets.QWidget()
        self.nhanvien.setObjectName("nhanvien")
        self.btn_suanv = QtWidgets.QPushButton(parent=self.nhanvien)
        self.btn_suanv.setGeometry(QtCore.QRect(420, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_suanv.setFont(font)
        self.btn_suanv.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_suanv.setObjectName("btn_suanv")
        self.label_15 = QtWidgets.QLabel(parent=self.nhanvien)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_15.setObjectName("label_15")
        self.btn_xoanv = QtWidgets.QPushButton(parent=self.nhanvien)
        self.btn_xoanv.setGeometry(QtCore.QRect(220, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoanv.setFont(font)
        self.btn_xoanv.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xoanv.setObjectName("btn_xoanv")
        self.btn_timkiemnv = QtWidgets.QPushButton(parent=self.nhanvien)
        self.btn_timkiemnv.setGeometry(QtCore.QRect(690, 80, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_timkiemnv.setFont(font)
        self.btn_timkiemnv.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_timkiemnv.setObjectName("btn_timkiemnv")
        self.btn_themnv = QtWidgets.QPushButton(parent=self.nhanvien)
        self.btn_themnv.setGeometry(QtCore.QRect(20, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_themnv.setFont(font)
        self.btn_themnv.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_themnv.setObjectName("btn_themnv")
        self.cbo_nv = QtWidgets.QComboBox(parent=self.nhanvien)
        self.cbo_nv.setGeometry(QtCore.QRect(20, 70, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cbo_nv.setFont(font)
        self.cbo_nv.setStyleSheet("QComboBox {\n"
"    \n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"font: 81 12pt \"Rockwell Extra Bold\";\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }\n"
"")
        self.cbo_nv.setObjectName("cbo_nv")
        self.cbo_nv.addItem("")
        self.cbo_nv.setItemText(0, "")
        self.cbo_nv.addItem("")
        self.cbo_nv.setItemText(1, "")
        self.txt_timkiemnv = QtWidgets.QTextEdit(parent=self.nhanvien)
        self.txt_timkiemnv.setGeometry(QtCore.QRect(290, 70, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_timkiemnv.setFont(font)
        self.txt_timkiemnv.setStyleSheet("background-color: rgb(248, 236, 240);\n"
"border: 3px solid #ffffff;  /* Viền màu hồng */\n"
"        border-radius: 20px;\n"
"        padding: 5px 10px;")
        self.txt_timkiemnv.setObjectName("txt_timkiemnv")
        self.tb_nhanvien = QtWidgets.QTableView(parent=self.nhanvien)
        self.tb_nhanvien.setGeometry(QtCore.QRect(30, 140, 791, 411))
        self.tb_nhanvien.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tb_nhanvien.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tb_nhanvien.setAlternatingRowColors(True)
        self.tb_nhanvien.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tb_nhanvien.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tb_nhanvien.setObjectName("tb_nhanvien")
        self.btn_refreshnv = QtWidgets.QPushButton(parent=self.nhanvien)
        self.btn_refreshnv.setGeometry(QtCore.QRect(620, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_refreshnv.setFont(font)
        self.btn_refreshnv.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_refreshnv.setObjectName("btn_refreshnv")
        self.Menu.addWidget(self.nhanvien)
        self.donhang = QtWidgets.QWidget()
        self.donhang.setObjectName("donhang")
        self.label_11 = QtWidgets.QLabel(parent=self.donhang)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_11.setObjectName("label_11")
        self.btn_suadh = QtWidgets.QPushButton(parent=self.donhang)
        self.btn_suadh.setGeometry(QtCore.QRect(460, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_suadh.setFont(font)
        self.btn_suadh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_suadh.setObjectName("btn_suadh")
        self.cbo_trangthai = QtWidgets.QComboBox(parent=self.donhang)
        self.cbo_trangthai.setGeometry(QtCore.QRect(10, 80, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cbo_trangthai.setFont(font)
        self.cbo_trangthai.setStyleSheet("QComboBox {\n"
"    \n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"font: 81 12pt \"Rockwell Extra Bold\";\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }\n"
"")
        self.cbo_trangthai.setObjectName("cbo_trangthai")
        self.cbo_trangthai.addItem("")
        self.cbo_trangthai.setItemText(0, "")
        self.cbo_trangthai.addItem("")
        self.cbo_trangthai.setItemText(1, "")
        self.btn_themdh = QtWidgets.QPushButton(parent=self.donhang)
        self.btn_themdh.setGeometry(QtCore.QRect(270, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_themdh.setFont(font)
        self.btn_themdh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_themdh.setObjectName("btn_themdh")
        self.tb_donhang = QtWidgets.QTableView(parent=self.donhang)
        self.tb_donhang.setGeometry(QtCore.QRect(30, 150, 791, 411))
        self.tb_donhang.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tb_donhang.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tb_donhang.setAlternatingRowColors(True)
        self.tb_donhang.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tb_donhang.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tb_donhang.setObjectName("tb_donhang")
        self.btn_refreshdh = QtWidgets.QPushButton(parent=self.donhang)
        self.btn_refreshdh.setGeometry(QtCore.QRect(630, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_refreshdh.setFont(font)
        self.btn_refreshdh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_refreshdh.setObjectName("btn_refreshdh")
        self.btn_xemCT = QtWidgets.QPushButton(parent=self.donhang)
        self.btn_xemCT.setGeometry(QtCore.QRect(650, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xemCT.setFont(font)
        self.btn_xemCT.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xemCT.setObjectName("btn_xemCT")
        self.Menu.addWidget(self.donhang)
        self.khachhang = QtWidgets.QWidget()
        self.khachhang.setObjectName("khachhang")
        self.cbo_kh = QtWidgets.QComboBox(parent=self.khachhang)
        self.cbo_kh.setGeometry(QtCore.QRect(20, 70, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cbo_kh.setFont(font)
        self.cbo_kh.setStyleSheet("QComboBox {\n"
"    \n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"font: 81 12pt \"Rockwell Extra Bold\";\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }\n"
"")
        self.cbo_kh.setObjectName("cbo_kh")
        self.txt_timkiemkh = QtWidgets.QTextEdit(parent=self.khachhang)
        self.txt_timkiemkh.setGeometry(QtCore.QRect(280, 70, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_timkiemkh.setFont(font)
        self.txt_timkiemkh.setStyleSheet("background-color: rgb(248, 236, 240);\n"
"border: 3px solid #ffffff;  /* Viền màu hồng */\n"
"        border-radius: 20px;\n"
"        padding: 5px 10px;")
        self.txt_timkiemkh.setObjectName("txt_timkiemkh")
        self.btn_suakh = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_suakh.setGeometry(QtCore.QRect(440, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_suakh.setFont(font)
        self.btn_suakh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_suakh.setObjectName("btn_suakh")
        self.label_8 = QtWidgets.QLabel(parent=self.khachhang)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_8.setObjectName("label_8")
        self.btn_themkh = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_themkh.setGeometry(QtCore.QRect(40, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_themkh.setFont(font)
        self.btn_themkh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_themkh.setObjectName("btn_themkh")
        self.btn_xoakh = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_xoakh.setGeometry(QtCore.QRect(240, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoakh.setFont(font)
        self.btn_xoakh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xoakh.setObjectName("btn_xoakh")
        self.btn_timkiemkh = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_timkiemkh.setGeometry(QtCore.QRect(690, 80, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_timkiemkh.setFont(font)
        self.btn_timkiemkh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_timkiemkh.setObjectName("btn_timkiemkh")
        self.tb_khachhang = QtWidgets.QTableView(parent=self.khachhang)
        self.tb_khachhang.setGeometry(QtCore.QRect(30, 140, 791, 411))
        self.tb_khachhang.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tb_khachhang.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tb_khachhang.setAlternatingRowColors(True)
        self.tb_khachhang.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tb_khachhang.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tb_khachhang.setObjectName("tb_khachhang")
        self.btn_refreshKH = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_refreshKH.setGeometry(QtCore.QRect(630, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_refreshKH.setFont(font)
        self.btn_refreshKH.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_refreshKH.setObjectName("btn_refreshKH")
        self.Menu.addWidget(self.khachhang)
        self.nhaccap = QtWidgets.QWidget()
        self.nhaccap.setObjectName("nhaccap")
        self.label_16 = QtWidgets.QLabel(parent=self.nhaccap)
        self.label_16.setGeometry(QtCore.QRect(20, 10, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_16.setObjectName("label_16")
        self.cbo_diachi = QtWidgets.QComboBox(parent=self.nhaccap)
        self.cbo_diachi.setGeometry(QtCore.QRect(20, 70, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cbo_diachi.setFont(font)
        self.cbo_diachi.setStyleSheet("QComboBox {\n"
"    \n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"font: 81 12pt \"Rockwell Extra Bold\";\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }\n"
"")
        self.cbo_diachi.setObjectName("cbo_diachi")
        self.cbo_diachi.addItem("")
        self.cbo_diachi.setItemText(0, "")
        self.cbo_diachi.addItem("")
        self.cbo_diachi.setItemText(1, "")
        self.tb_nhaccap = QtWidgets.QTableView(parent=self.nhaccap)
        self.tb_nhaccap.setGeometry(QtCore.QRect(30, 140, 791, 411))
        self.tb_nhaccap.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tb_nhaccap.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tb_nhaccap.setAlternatingRowColors(True)
        self.tb_nhaccap.setObjectName("tb_nhaccap")
        self.btn_xoancc = QtWidgets.QPushButton(parent=self.nhaccap)
        self.btn_xoancc.setGeometry(QtCore.QRect(240, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoancc.setFont(font)
        self.btn_xoancc.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xoancc.setObjectName("btn_xoancc")
        self.btn_suancc = QtWidgets.QPushButton(parent=self.nhaccap)
        self.btn_suancc.setGeometry(QtCore.QRect(430, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_suancc.setFont(font)
        self.btn_suancc.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_suancc.setObjectName("btn_suancc")
        self.btn_themncc = QtWidgets.QPushButton(parent=self.nhaccap)
        self.btn_themncc.setGeometry(QtCore.QRect(50, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_themncc.setFont(font)
        self.btn_themncc.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_themncc.setObjectName("btn_themncc")
        self.btn_refreshncc = QtWidgets.QPushButton(parent=self.nhaccap)
        self.btn_refreshncc.setGeometry(QtCore.QRect(620, 560, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_refreshncc.setFont(font)
        self.btn_refreshncc.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_refreshncc.setObjectName("btn_refreshncc")
        self.btn_timkiemncc = QtWidgets.QPushButton(parent=self.nhaccap)
        self.btn_timkiemncc.setGeometry(QtCore.QRect(690, 80, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_timkiemncc.setFont(font)
        self.btn_timkiemncc.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_timkiemncc.setObjectName("btn_timkiemncc")
        self.txt_timkiemncc = QtWidgets.QTextEdit(parent=self.nhaccap)
        self.txt_timkiemncc.setGeometry(QtCore.QRect(280, 70, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_timkiemncc.setFont(font)
        self.txt_timkiemncc.setStyleSheet("background-color: rgb(248, 236, 240);\n"
"border: 3px solid #ffffff;  /* Viền màu hồng */\n"
"        border-radius: 20px;\n"
"        padding: 5px 10px;")
        self.txt_timkiemncc.setObjectName("txt_timkiemncc")
        self.Menu.addWidget(self.nhaccap)
        UIMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=UIMainWindow)
        self.statusbar.setObjectName("statusbar")
        UIMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UIMainWindow)
        self.Menu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UIMainWindow)

    def retranslateUi(self, UIMainWindow):
        _translate = QtCore.QCoreApplication.translate
        UIMainWindow.setWindowTitle(_translate("UIMainWindow", "MainWindow"))
        self.label_12.setText(_translate("UIMainWindow", "Mini Pet"))
        self.btn_home.setText(_translate("UIMainWindow", "Trang chủ"))
        self.btn_spham.setText(_translate("UIMainWindow", "Sản phẩm"))
        self.btn_nhanvien.setText(_translate("UIMainWindow", "Nhân Viên"))
        self.btn_donhang.setText(_translate("UIMainWindow", "Đơn hàng"))
        self.btn_khachhang.setText(_translate("UIMainWindow", "Khách hàng"))
        self.btn_nhacc.setText(_translate("UIMainWindow", "Nhà cung cấp"))
        self.btn_logout.setText(_translate("UIMainWindow", "Đăng xuất"))
        self.label_3.setText(_translate("UIMainWindow", "TRANG CHỦ"))
        self.label_25.setText(_translate("UIMainWindow", "Số hóa đơn trong ngày"))
        self.lbl_dh.setText(_translate("UIMainWindow", "TextLabel"))
        self.label_27.setText(_translate("UIMainWindow", "Doanh thu trong ngày"))
        self.lbl_dt.setText(_translate("UIMainWindow", "TextLabel"))
        self.label_30.setText(_translate("UIMainWindow", "Sản phẩm bán trong ngày"))
        self.lbl_sp.setText(_translate("UIMainWindow", "TextLabel"))
        self.btn_suasp.setText(_translate("UIMainWindow", "CẬP NHẬT"))
        self.btn_xoasp.setText(_translate("UIMainWindow", "XÓA"))
        self.btn_themsp.setText(_translate("UIMainWindow", "THÊM"))
        self.label_10.setText(_translate("UIMainWindow", "SẢN PHẨM"))
        self.txt_timkimsp.setPlaceholderText(_translate("UIMainWindow", "Tìm kiếm theo tên sản phẩm"))
        self.btn_timkiemsp.setText(_translate("UIMainWindow", "Tìm"))
        self.btn_refresh.setText(_translate("UIMainWindow", "RESET"))
        self.btn_suanv.setText(_translate("UIMainWindow", "CẬP NHẬT"))
        self.label_15.setText(_translate("UIMainWindow", "NHÂN VIÊN"))
        self.btn_xoanv.setText(_translate("UIMainWindow", "XÓA"))
        self.btn_timkiemnv.setText(_translate("UIMainWindow", "Tìm"))
        self.btn_themnv.setText(_translate("UIMainWindow", "THÊM"))
        self.txt_timkiemnv.setPlaceholderText(_translate("UIMainWindow", "Tìm kiếm theo tên nhân viên"))
        self.btn_refreshnv.setText(_translate("UIMainWindow", "RESET"))
        self.label_11.setText(_translate("UIMainWindow", "ĐƠN HÀNG"))
        self.btn_suadh.setText(_translate("UIMainWindow", "CẬP NHẬT"))
        self.btn_themdh.setText(_translate("UIMainWindow", "THÊM"))
        self.btn_refreshdh.setText(_translate("UIMainWindow", "RESET"))
        self.btn_xemCT.setText(_translate("UIMainWindow", "CHI TIẾT"))
        self.txt_timkiemkh.setPlaceholderText(_translate("UIMainWindow", "Tìm kiếm theo email/ số điện thoại"))
        self.btn_suakh.setText(_translate("UIMainWindow", "CẬP NHẬT"))
        self.label_8.setText(_translate("UIMainWindow", "KHÁCH HÀNG"))
        self.btn_themkh.setText(_translate("UIMainWindow", "THÊM"))
        self.btn_xoakh.setText(_translate("UIMainWindow", "XÓA"))
        self.btn_timkiemkh.setText(_translate("UIMainWindow", "Tìm"))
        self.btn_refreshKH.setText(_translate("UIMainWindow", "RESET"))
        self.label_16.setText(_translate("UIMainWindow", "NHÀ CUNG CẤP"))
        self.btn_xoancc.setText(_translate("UIMainWindow", "XÓA"))
        self.btn_suancc.setText(_translate("UIMainWindow", "CẬP NHẬT"))
        self.btn_themncc.setText(_translate("UIMainWindow", "THÊM"))
        self.btn_refreshncc.setText(_translate("UIMainWindow", "RESET"))
        self.btn_timkiemncc.setText(_translate("UIMainWindow", "Tìm"))
        self.txt_timkiemncc.setPlaceholderText(_translate("UIMainWindow", "Nhập tên nhà cung cấp cần tìm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UIMainWindow = QtWidgets.QMainWindow()
    ui = Ui_UIMainWindow()
    ui.setupUi(UIMainWindow)
    UIMainWindow.show()
    sys.exit(app.exec())
