# Form implementation generated from reading ui file 'NhaCungCap/updateNCC.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 468)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_email = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(310, 190, 261, 41))
        self.txt_email.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_email.setObjectName("txt_email")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(40, 10, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("color: rgb(149, 106, 214);\n"
"font: 87 22pt \"Segoe UI Black\";")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.btn_luu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_luu.setGeometry(QtCore.QRect(210, 370, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_luu.setFont(font)
        self.btn_luu.setObjectName("btn_luu")
        self.txt_tenNCC = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_tenNCC.setGeometry(QtCore.QRect(30, 190, 261, 41))
        self.txt_tenNCC.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_tenNCC.setObjectName("txt_tenNCC")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 160, 81, 21))
        self.label_3.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 80, 161, 21))
        self.label_4.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 250, 101, 31))
        self.label_2.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 160, 211, 21))
        self.label.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label.setObjectName("label")
        self.txt_diachi = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_diachi.setGeometry(QtCore.QRect(30, 280, 261, 41))
        self.txt_diachi.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_diachi.setObjectName("txt_diachi")
        self.txt_sdt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_sdt.setGeometry(QtCore.QRect(310, 110, 261, 41))
        self.txt_sdt.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_sdt.setObjectName("txt_sdt")
        self.txt_maNCC = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_maNCC.setGeometry(QtCore.QRect(30, 110, 261, 41))
        self.txt_maNCC.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_maNCC.setObjectName("txt_maNCC")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 80, 201, 21))
        self.label_5.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 250, 101, 21))
        self.label_6.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_6.setObjectName("label_6")
        self.txt_note = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_note.setGeometry(QtCore.QRect(310, 280, 261, 41))
        self.txt_note.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_note.setObjectName("txt_note")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "CẬP NHẬT NHÀ CUNG CẤP"))
        self.btn_luu.setStyleSheet(_translate("MainWindow", "background-color: rgb(255, 255, 215); color: rgb(149, 106, 214); border-radius: 10px;"))
        self.btn_luu.setText(_translate("MainWindow", "LƯU"))
        self.label_3.setText(_translate("MainWindow", "EMAIL"))
        self.label_4.setText(_translate("MainWindow", "SỐ ĐIỆN THOẠI"))
        self.label_2.setText(_translate("MainWindow", "ĐỊA CHỈ"))
        self.label.setText(_translate("MainWindow", "TÊN NHÀ CUNG CẤP"))
        self.label_5.setText(_translate("MainWindow", "MÃ NHÀ CUNG CẤP"))
        self.label_6.setText(_translate("MainWindow", "GHI CHÚ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
