# Form implementation generated from reading ui file 'Nhanvien/updateNV.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_updateNV(object):
    def setupUi(self, updateNV):
        updateNV.setObjectName("updateNV")
        updateNV.resize(624, 538)
        self.txt_sdt = QtWidgets.QTextEdit(parent=updateNV)
        self.txt_sdt.setGeometry(QtCore.QRect(330, 90, 261, 41))
        self.txt_sdt.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_sdt.setObjectName("txt_sdt")
        self.labelTitle = QtWidgets.QLabel(parent=updateNV)
        self.labelTitle.setGeometry(QtCore.QRect(110, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.label_3 = QtWidgets.QLabel(parent=updateNV)
        self.label_3.setGeometry(QtCore.QRect(130, 310, 81, 21))
        self.label_3.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=updateNV)
        self.label_2.setGeometry(QtCore.QRect(120, 230, 101, 31))
        self.label_2.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=updateNV)
        self.label_5.setGeometry(QtCore.QRect(430, 230, 61, 21))
        self.label_5.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_5.setObjectName("label_5")
        self.btn_luunv = QtWidgets.QPushButton(parent=updateNV)
        self.btn_luunv.setGeometry(QtCore.QRect(210, 440, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_luunv.setFont(font)
        self.btn_luunv.setObjectName("btn_luunv")
        self.txt_vitri = QtWidgets.QTextEdit(parent=updateNV)
        self.txt_vitri.setGeometry(QtCore.QRect(330, 260, 261, 41))
        self.txt_vitri.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_vitri.setObjectName("txt_vitri")
        self.label = QtWidgets.QLabel(parent=updateNV)
        self.label.setGeometry(QtCore.QRect(90, 135, 171, 31))
        self.label.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label.setObjectName("label")
        self.txt_luong = QtWidgets.QTextEdit(parent=updateNV)
        self.txt_luong.setGeometry(QtCore.QRect(330, 180, 261, 41))
        self.txt_luong.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_luong.setObjectName("txt_luong")
        self.txt_email = QtWidgets.QTextEdit(parent=updateNV)
        self.txt_email.setGeometry(QtCore.QRect(40, 340, 261, 41))
        self.txt_email.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_email.setObjectName("txt_email")
        self.txt_diachi = QtWidgets.QTextEdit(parent=updateNV)
        self.txt_diachi.setGeometry(QtCore.QRect(40, 260, 261, 41))
        self.txt_diachi.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_diachi.setObjectName("txt_diachi")
        self.label_6 = QtWidgets.QLabel(parent=updateNV)
        self.label_6.setGeometry(QtCore.QRect(420, 150, 91, 21))
        self.label_6.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_6.setObjectName("label_6")
        self.txt_tennv = QtWidgets.QTextEdit(parent=updateNV)
        self.txt_tennv.setGeometry(QtCore.QRect(40, 170, 261, 41))
        self.txt_tennv.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_tennv.setObjectName("txt_tennv")
        self.label_4 = QtWidgets.QLabel(parent=updateNV)
        self.label_4.setGeometry(QtCore.QRect(360, 60, 161, 21))
        self.label_4.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_4.setObjectName("label_4")
        self.txt_manv = QtWidgets.QTextEdit(parent=updateNV)
        self.txt_manv.setGeometry(QtCore.QRect(40, 90, 261, 41))
        self.txt_manv.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_manv.setObjectName("txt_manv")
        self.label_7 = QtWidgets.QLabel(parent=updateNV)
        self.label_7.setGeometry(QtCore.QRect(90, 55, 171, 31))
        self.label_7.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_7.setObjectName("label_7")
        self.txt_note = QtWidgets.QTextEdit(parent=updateNV)
        self.txt_note.setGeometry(QtCore.QRect(330, 340, 261, 41))
        self.txt_note.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_note.setObjectName("txt_note")
        self.label_8 = QtWidgets.QLabel(parent=updateNV)
        self.label_8.setGeometry(QtCore.QRect(410, 310, 101, 21))
        self.label_8.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_8.setObjectName("label_8")

        self.retranslateUi(updateNV)
        QtCore.QMetaObject.connectSlotsByName(updateNV)

    def retranslateUi(self, updateNV):
        _translate = QtCore.QCoreApplication.translate
        updateNV.setWindowTitle(_translate("updateNV", "Form"))
        self.labelTitle.setStyleSheet(_translate("updateNV", "color: rgb(149, 106, 214);"))
        self.labelTitle.setText(_translate("updateNV", "CẬP NHẬT NHÂN VIÊN"))
        self.label_3.setText(_translate("updateNV", "EMAIL"))
        self.label_2.setText(_translate("updateNV", "ĐỊA CHỈ"))
        self.label_5.setText(_translate("updateNV", "VỊ TRÍ"))
        self.btn_luunv.setStyleSheet(_translate("updateNV", "background-color: rgb(255, 255, 215); color: rgb(149, 106, 214); border-radius: 10px;"))
        self.btn_luunv.setText(_translate("updateNV", "LƯU"))
        self.label.setText(_translate("updateNV", "TÊN NHÂN VIÊN"))
        self.label_6.setText(_translate("updateNV", "LƯƠNG"))
        self.label_4.setText(_translate("updateNV", "SỐ ĐIỆN THOẠI"))
        self.label_7.setText(_translate("updateNV", "MÃ NHÂN VIÊN"))
        self.label_8.setText(_translate("updateNV", "GHI CHÚ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    updateNV = QtWidgets.QWidget()
    ui = Ui_updateNV()
    ui.setupUi(updateNV)
    updateNV.show()
    sys.exit(app.exec())
