# Form implementation generated from reading ui file 'UI/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UIMainWindow(object):
    def setupUi(self, UIMainWindow):
        UIMainWindow.setObjectName("UIMainWindow")
        UIMainWindow.resize(1203, 695)
        UIMainWindow.setStyleSheet("background-color: rgb(255, 255, 215);")
        self.centralwidget = QtWidgets.QWidget(parent=UIMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 600, 61, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("UI\\hinhanh/user.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 75 30pt \"Segoe Script\";\n"
"")
        self.label_12.setObjectName("label_12")
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(60, 80, 81, 81))
        self.widget_3.setStyleSheet("background-image: url(\"E:/HK6/DoAN/DoAn/hinhanh/logo2.png\");\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;  /* Ảnh sẽ tự động căn chỉnh để phủ toàn bộ */\n"
"\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.btn_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(20, 540, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_logout.setObjectName("btn_logout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 160, 241, 371))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_home = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_home.setFont(font)
        self.btn_home.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\\../hinhanh/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout.addWidget(self.btn_home)
        self.btn_spham = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_spham.setFont(font)
        self.btn_spham.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_spham.setObjectName("btn_spham")
        self.verticalLayout.addWidget(self.btn_spham)
        self.btn_nhanvien = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_nhanvien.setFont(font)
        self.btn_nhanvien.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI\\../hinhanh/4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_nhanvien.setIcon(icon1)
        self.btn_nhanvien.setObjectName("btn_nhanvien")
        self.verticalLayout.addWidget(self.btn_nhanvien)
        self.btn_donhang = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_donhang.setFont(font)
        self.btn_donhang.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_donhang.setObjectName("btn_donhang")
        self.verticalLayout.addWidget(self.btn_donhang)
        self.btn_khachhang = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_khachhang.setFont(font)
        self.btn_khachhang.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_khachhang.setObjectName("btn_khachhang")
        self.verticalLayout.addWidget(self.btn_khachhang)
        self.btn_nhacc = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_nhacc.setFont(font)
        self.btn_nhacc.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_nhacc.setObjectName("btn_nhacc")
        self.verticalLayout.addWidget(self.btn_nhacc)
        self.Menu = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.Menu.setGeometry(QtCore.QRect(270, 30, 881, 621))
        self.Menu.setStyleSheet("background-color:rgb(248, 236, 240);\n"
"\n"
"border-radius: 20px; /* Bo góc */;")
        self.Menu.setObjectName("Menu")
        self.trangchu = QtWidgets.QWidget()
        self.trangchu.setObjectName("trangchu")
        self.label_3 = QtWidgets.QLabel(parent=self.trangchu)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_3.setObjectName("label_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.trangchu)
        self.widget_2.setGeometry(QtCore.QRect(20, 60, 841, 151))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bill_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.bill_4.setStyleSheet("background-color: rgb(255, 253, 188);\n"
"color: rgb(255, 239, 178);\n"
"   border-radius: 20px; /* Bo góc */;")
        self.bill_4.setObjectName("bill_4")
        self.label_25 = QtWidgets.QLabel(parent=self.bill_4)
        self.label_25.setGeometry(QtCore.QRect(10, 0, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 87 12pt \"Arial\";\n"
"")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.bill_4)
        self.label_26.setGeometry(QtCore.QRect(200, 50, 41, 41))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("UI\\../hinhanh/bill1.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.bill_4)
        self.dthu_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.dthu_4.setStyleSheet("background-color: rgb(195, 255, 188);\n"
" border-radius: 20px; /* Bo góc */;")
        self.dthu_4.setObjectName("dthu_4")
        self.label_27 = QtWidgets.QLabel(parent=self.dthu_4)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 87 12pt \"Arial\";\n"
"\n"
"")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.dthu_4)
        self.label_28.setGeometry(QtCore.QRect(130, 50, 41, 41))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("UI\\../hinhanh/dthu1.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_2.addWidget(self.dthu_4)
        self.spham_4 = QtWidgets.QWidget(parent=self.widget_2)
        self.spham_4.setStyleSheet("background-color: rgb(255, 253, 188);\n"
"color: rgb(255, 239, 178);\n"
"   border-radius: 20px; /* Bo góc */;")
        self.spham_4.setObjectName("spham_4")
        self.label_29 = QtWidgets.QLabel(parent=self.spham_4)
        self.label_29.setGeometry(QtCore.QRect(190, 60, 41, 41))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("UI\\../hinhanh/spham.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.spham_4)
        self.label_30.setGeometry(QtCore.QRect(10, 0, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(241, 121, 184);\n"
"font: 87 12pt \"Arial\";\n"
"\n"
"")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.spham_4)
        self.Menu.addWidget(self.trangchu)
        self.sanpham = QtWidgets.QWidget()
        self.sanpham.setObjectName("sanpham")
        self.btn_suasp = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_suasp.setGeometry(QtCore.QRect(440, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_suasp.setFont(font)
        self.btn_suasp.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_suasp.setObjectName("btn_suasp")
        self.btn_xoasp = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_xoasp.setGeometry(QtCore.QRect(240, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoasp.setFont(font)
        self.btn_xoasp.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xoasp.setObjectName("btn_xoasp")
        self.cbo_sp = QtWidgets.QComboBox(parent=self.sanpham)
        self.cbo_sp.setGeometry(QtCore.QRect(20, 90, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cbo_sp.setFont(font)
        self.cbo_sp.setStyleSheet("QComboBox {\n"
"    \n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"font: 81 12pt \"Rockwell Extra Bold\";\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }\n"
"")
        self.cbo_sp.setObjectName("cbo_sp")
        self.cbo_sp.addItem("")
        self.cbo_sp.addItem("")
        self.cbo_sp.addItem("")
        self.cbo_sp.setItemText(2, "")
        self.cbo_sp.addItem("")
        self.cbo_sp.setItemText(3, "")
        self.btn_themsp = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_themsp.setGeometry(QtCore.QRect(40, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_themsp.setFont(font)
        self.btn_themsp.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_themsp.setObjectName("btn_themsp")
        self.label_10 = QtWidgets.QLabel(parent=self.sanpham)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_10.setObjectName("label_10")
        self.tb_sanpham = QtWidgets.QTableView(parent=self.sanpham)
        self.tb_sanpham.setGeometry(QtCore.QRect(30, 180, 801, 371))
        self.tb_sanpham.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tb_sanpham.setAlternatingRowColors(True)
        self.tb_sanpham.setObjectName("tb_sanpham")
        self.txt_timkimsp = QtWidgets.QTextEdit(parent=self.sanpham)
        self.txt_timkimsp.setGeometry(QtCore.QRect(300, 90, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_timkimsp.setFont(font)
        self.txt_timkimsp.setStyleSheet("background-color: rgb(248, 236, 240);\n"
"border: 3px solid #ffffff;  /* Viền màu hồng */\n"
"        border-radius: 20px;\n"
"        padding: 5px 10px;")
        self.txt_timkimsp.setObjectName("txt_timkimsp")
        self.btn_timkiemsp = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_timkiemsp.setGeometry(QtCore.QRect(700, 100, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_timkiemsp.setFont(font)
        self.btn_timkiemsp.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_timkiemsp.setObjectName("btn_timkiemsp")
        self.btn_refresh = QtWidgets.QPushButton(parent=self.sanpham)
        self.btn_refresh.setGeometry(QtCore.QRect(650, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_refresh.setFont(font)
        self.btn_refresh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_refresh.setObjectName("btn_refresh")
        self.Menu.addWidget(self.sanpham)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_11 = QtWidgets.QLabel(parent=self.page)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_11.setObjectName("label_11")
        self.btn_sua_4 = QtWidgets.QPushButton(parent=self.page)
        self.btn_sua_4.setGeometry(QtCore.QRect(680, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sua_4.setFont(font)
        self.btn_sua_4.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_sua_4.setObjectName("btn_sua_4")
        self.btn_xoa_4 = QtWidgets.QPushButton(parent=self.page)
        self.btn_xoa_4.setGeometry(QtCore.QRect(480, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoa_4.setFont(font)
        self.btn_xoa_4.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xoa_4.setObjectName("btn_xoa_4")
        self.cbo_dv_4 = QtWidgets.QComboBox(parent=self.page)
        self.cbo_dv_4.setGeometry(QtCore.QRect(30, 80, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cbo_dv_4.setFont(font)
        self.cbo_dv_4.setStyleSheet("QComboBox {\n"
"    \n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"font: 81 12pt \"Rockwell Extra Bold\";\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }\n"
"")
        self.cbo_dv_4.setObjectName("cbo_dv_4")
        self.cbo_dv_4.addItem("")
        self.cbo_dv_4.addItem("")
        self.cbo_dv_4.addItem("")
        self.cbo_dv_4.setItemText(2, "")
        self.cbo_dv_4.addItem("")
        self.cbo_dv_4.setItemText(3, "")
        self.btn_them_4 = QtWidgets.QPushButton(parent=self.page)
        self.btn_them_4.setGeometry(QtCore.QRect(290, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_them_4.setFont(font)
        self.btn_them_4.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_them_4.setObjectName("btn_them_4")
        self.tableView = QtWidgets.QTableView(parent=self.page)
        self.tableView.setGeometry(QtCore.QRect(50, 180, 791, 411))
        self.tableView.setStyleSheet("\n"
"    QTableView {\n"
"        background-color: #FFF5E1;  /* Màu nền */\n"
"        alternate-background-color: #FFDAB9;  /* Màu xen kẽ */\n"
"        gridline-color: #8B0000;  /* Màu đường kẻ */\n"
"        color: #000;  /* Màu chữ */\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #FF7F50;  /* Màu tiêu đề */\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"    }")
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setObjectName("tableView")
        self.Menu.addWidget(self.page)
        self.dichvu = QtWidgets.QWidget()
        self.dichvu.setObjectName("dichvu")
        self.label_5 = QtWidgets.QLabel(parent=self.dichvu)
        self.label_5.setGeometry(QtCore.QRect(30, 0, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_5.setObjectName("label_5")
        self.cbo_dv = QtWidgets.QComboBox(parent=self.dichvu)
        self.cbo_dv.setGeometry(QtCore.QRect(30, 60, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cbo_dv.setFont(font)
        self.cbo_dv.setStyleSheet("QComboBox {\n"
"    \n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"font: 81 12pt \"Rockwell Extra Bold\";\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }\n"
"")
        self.cbo_dv.setObjectName("cbo_dv")
        self.cbo_dv.addItem("")
        self.cbo_dv.addItem("")
        self.cbo_dv.addItem("")
        self.cbo_dv.setItemText(2, "")
        self.cbo_dv.addItem("")
        self.cbo_dv.setItemText(3, "")
        self.txt_timkiemnv = QtWidgets.QTextEdit(parent=self.dichvu)
        self.txt_timkiemnv.setGeometry(QtCore.QRect(310, 60, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_timkiemnv.setFont(font)
        self.txt_timkiemnv.setStyleSheet("background-color: rgb(248, 236, 240);\n"
"border: 3px solid #ffffff;  /* Viền màu hồng */\n"
"        border-radius: 20px;\n"
"        padding: 5px 10px;")
        self.txt_timkiemnv.setObjectName("txt_timkiemnv")
        self.btn_them = QtWidgets.QPushButton(parent=self.dichvu)
        self.btn_them.setGeometry(QtCore.QRect(160, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_them.setFont(font)
        self.btn_them.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_them.setObjectName("btn_them")
        self.btn_xoa = QtWidgets.QPushButton(parent=self.dichvu)
        self.btn_xoa.setGeometry(QtCore.QRect(360, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoa.setFont(font)
        self.btn_xoa.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xoa.setObjectName("btn_xoa")
        self.btn_sua = QtWidgets.QPushButton(parent=self.dichvu)
        self.btn_sua.setGeometry(QtCore.QRect(580, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sua.setFont(font)
        self.btn_sua.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_sua.setObjectName("btn_sua")
        self.btn_timkiemnv = QtWidgets.QPushButton(parent=self.dichvu)
        self.btn_timkiemnv.setGeometry(QtCore.QRect(740, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_timkiemnv.setFont(font)
        self.btn_timkiemnv.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_timkiemnv.setObjectName("btn_timkiemnv")
        self.Menu.addWidget(self.dichvu)
        self.khachhang = QtWidgets.QWidget()
        self.khachhang.setObjectName("khachhang")
        self.cbo_kh = QtWidgets.QComboBox(parent=self.khachhang)
        self.cbo_kh.setGeometry(QtCore.QRect(10, 60, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cbo_kh.setFont(font)
        self.cbo_kh.setStyleSheet("QComboBox {\n"
"          background-color: white;\n"
"          border: 2px solid #ccc;\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }")
        self.cbo_kh.setObjectName("cbo_kh")
        self.cbo_kh.addItem("")
        self.cbo_kh.addItem("")
        self.txt_timkiemkh = QtWidgets.QTextEdit(parent=self.khachhang)
        self.txt_timkiemkh.setGeometry(QtCore.QRect(300, 60, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_timkiemkh.setFont(font)
        self.txt_timkiemkh.setStyleSheet("background-color: rgb(248, 236, 240);\n"
"border: 3px solid #ffffff;  /* Viền màu hồng */\n"
"        border-radius: 20px;\n"
"        padding: 5px 10px;")
        self.txt_timkiemkh.setObjectName("txt_timkiemkh")
        self.btn_sua2 = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_sua2.setGeometry(QtCore.QRect(560, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sua2.setFont(font)
        self.btn_sua2.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_sua2.setObjectName("btn_sua2")
        self.label_8 = QtWidgets.QLabel(parent=self.khachhang)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(149, 106, 214);")
        self.label_8.setObjectName("label_8")
        self.btn_them2 = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_them2.setGeometry(QtCore.QRect(140, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_them2.setFont(font)
        self.btn_them2.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_them2.setObjectName("btn_them2")
        self.btn_xoa2 = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_xoa2.setGeometry(QtCore.QRect(340, 570, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_xoa2.setFont(font)
        self.btn_xoa2.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_xoa2.setObjectName("btn_xoa2")
        self.btn_timkiemkh = QtWidgets.QPushButton(parent=self.khachhang)
        self.btn_timkiemkh.setGeometry(QtCore.QRect(710, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_timkiemkh.setFont(font)
        self.btn_timkiemkh.setStyleSheet("QPushButton {\n"
"    background-color:rgb(255, 255, 215); /* Màu nền xanh dương */\n"
"    /* Màu chữ trắng rgb(255, 255, 215)*/\n"
"    color: rgb(149, 106, 214);\n"
"    border-radius: 10px; /* Bo góc */\n"
"}\n"
"QPushButton:hover {\n"
" /* Màu nền khi rê chuột */\n"
"    background-color: rgb(108, 187, 174);\n"
"color: white\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(31, 97, 141); /* Màu nền khi nhấn */\n"
"}")
        self.btn_timkiemkh.setObjectName("btn_timkiemkh")
        self.Menu.addWidget(self.khachhang)
        UIMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=UIMainWindow)
        self.statusbar.setObjectName("statusbar")
        UIMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UIMainWindow)
        self.Menu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(UIMainWindow)

    def retranslateUi(self, UIMainWindow):
        _translate = QtCore.QCoreApplication.translate
        UIMainWindow.setWindowTitle(_translate("UIMainWindow", "MainWindow"))
        self.label_12.setText(_translate("UIMainWindow", "Mini Pet"))
        self.btn_logout.setText(_translate("UIMainWindow", "Đăng xuất"))
        self.btn_home.setText(_translate("UIMainWindow", "Trang chủ"))
        self.btn_spham.setText(_translate("UIMainWindow", "Sản phẩm"))
        self.btn_nhanvien.setText(_translate("UIMainWindow", "Nhân Viên"))
        self.btn_donhang.setText(_translate("UIMainWindow", "Đơn hàng"))
        self.btn_khachhang.setText(_translate("UIMainWindow", "Khách hàng"))
        self.btn_nhacc.setText(_translate("UIMainWindow", "Nhà cung cấp"))
        self.label_3.setText(_translate("UIMainWindow", "TRANG CHỦ"))
        self.label_25.setText(_translate("UIMainWindow", "Số hóa đơn trong ngày"))
        self.label_27.setText(_translate("UIMainWindow", "Doanh thu trong ngày"))
        self.label_30.setText(_translate("UIMainWindow", "Sản phẩm bán trong ngày"))
        self.btn_suasp.setText(_translate("UIMainWindow", "SỬA"))
        self.btn_xoasp.setText(_translate("UIMainWindow", "XÓA"))
        self.cbo_sp.setItemText(0, _translate("UIMainWindow", "Từ A -Z"))
        self.cbo_sp.setItemText(1, _translate("UIMainWindow", "Từ Z-A"))
        self.btn_themsp.setText(_translate("UIMainWindow", "THÊM"))
        self.label_10.setText(_translate("UIMainWindow", "SẢN PHẨM"))
        self.txt_timkimsp.setPlaceholderText(_translate("UIMainWindow", "Tìm kiếm"))
        self.btn_timkiemsp.setText(_translate("UIMainWindow", "Tìm"))
        self.btn_refresh.setText(_translate("UIMainWindow", "CẬP NHẬT"))
        self.label_11.setText(_translate("UIMainWindow", "ĐƠN HÀNG"))
        self.btn_sua_4.setText(_translate("UIMainWindow", "SỬA"))
        self.btn_xoa_4.setText(_translate("UIMainWindow", "XÓA"))
        self.cbo_dv_4.setItemText(0, _translate("UIMainWindow", "Từ A -Z"))
        self.cbo_dv_4.setItemText(1, _translate("UIMainWindow", "Từ Z-A"))
        self.btn_them_4.setText(_translate("UIMainWindow", "THÊM"))
        self.label_5.setText(_translate("UIMainWindow", "NHÂN VIÊN"))
        self.cbo_dv.setItemText(0, _translate("UIMainWindow", "Từ A -Z"))
        self.cbo_dv.setItemText(1, _translate("UIMainWindow", "Từ Z-A"))
        self.txt_timkiemnv.setPlaceholderText(_translate("UIMainWindow", "Tìm kiếm"))
        self.btn_them.setText(_translate("UIMainWindow", "THÊM"))
        self.btn_xoa.setText(_translate("UIMainWindow", "XÓA"))
        self.btn_sua.setText(_translate("UIMainWindow", "SỬA"))
        self.btn_timkiemnv.setText(_translate("UIMainWindow", "Tìm"))
        self.cbo_kh.setItemText(0, _translate("UIMainWindow", "Từ A-Z"))
        self.cbo_kh.setItemText(1, _translate("UIMainWindow", "Từ Z-A"))
        self.txt_timkiemkh.setPlaceholderText(_translate("UIMainWindow", "Nhập tìm khác hàng cần tìm"))
        self.btn_sua2.setText(_translate("UIMainWindow", "SỬA"))
        self.label_8.setText(_translate("UIMainWindow", "KHÁCH HÀNG"))
        self.btn_them2.setText(_translate("UIMainWindow", "THÊM"))
        self.btn_xoa2.setText(_translate("UIMainWindow", "XÓA"))
        self.btn_timkiemkh.setText(_translate("UIMainWindow", "Tìm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UIMainWindow = QtWidgets.QMainWindow()
    ui = Ui_UIMainWindow()
    ui.setupUi(UIMainWindow)
    UIMainWindow.show()
    sys.exit(app.exec())
