# Form implementation generated from reading ui file '.\UI\update.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Update(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 578)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(160, 0, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.txt_soluongP = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_soluongP.setGeometry(QtCore.QRect(20, 275, 261, 41))
        self.txt_soluongP.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_soluongP.setObjectName("txt_soluongP")
        self.cbo_danhmucSP = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbo_danhmucSP.setGeometry(QtCore.QRect(400, 100, 251, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbo_danhmucSP.setFont(font)
        self.cbo_danhmucSP.setStyleSheet("QComboBox {\n"
"          background-color: white;\n"
"          border: 3px solid #3498db;  /* Viền xanh dương */\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }")
        self.cbo_danhmucSP.setObjectName("cbo_danhmucSP")
        self.cbo_danhmucSP.addItem("")
        self.cbo_danhmucSP.addItem("")
        self.cbo_danhmucSP.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 410, 131, 21))
        self.label_5.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 65, 151, 31))
        self.label.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label.setObjectName("label")
        self.cbo_danhmucNCC = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbo_danhmucNCC.setGeometry(QtCore.QRect(20, 440, 261, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbo_danhmucNCC.setFont(font)
        self.cbo_danhmucNCC.setStyleSheet("QComboBox {\n"
"          background-color: white;\n"
"          border: 3px solid #3498db;  /* Viền xanh dương */\n"
"          border-radius: 10px;\n"
"          padding: 5px;\n"
"      }\n"
"      QComboBox::drop-down {\n"
"          border: none;\n"
"          background: transparent;\n"
"      }\n"
"      QComboBox::down-arrow {\n"
"          image: url(down-arrow.png); /* Thay bằng icon của bạn */\n"
"          width: 14px;\n"
"          height: 14px;\n"
"      }")
        self.cbo_danhmucNCC.setObjectName("cbo_danhmucNCC")
        self.lbl_anh = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_anh.setGeometry(QtCore.QRect(400, 160, 251, 211))
        self.lbl_anh.setScaledContents(True)
        self.lbl_anh.setObjectName("lbl_anh")
        self.btn_luusp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_luusp.setGeometry(QtCore.QRect(300, 470, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_luusp.setFont(font)
        self.btn_luusp.setStyleSheet("background-color: rgb(255, 255, 215); color: rgb(149, 106, 214); border-radius: 10px;\n"
"font: 75 16pt \"Tahoma\";")
        self.btn_luusp.setObjectName("btn_luusp")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 330, 141, 21))
        self.label_6.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 165, 171, 21))
        self.label_2.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_2.setObjectName("label_2")
        self.txt_giaSP = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_giaSP.setGeometry(QtCore.QRect(20, 355, 261, 41))
        self.txt_giaSP.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_giaSP.setObjectName("txt_giaSP")
        self.btn_chon_anh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_chon_anh.setGeometry(QtCore.QRect(440, 410, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_chon_anh.setFont(font)
        self.btn_chon_anh.setObjectName("btn_chon_anh")
        self.txt_tenSP = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_tenSP.setGeometry(QtCore.QRect(20, 190, 261, 41))
        self.txt_tenSP.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_tenSP.setObjectName("txt_tenSP")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 70, 131, 21))
        self.label_4.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_4.setObjectName("label_4")
        self.txt_maSP = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_maSP.setGeometry(QtCore.QRect(20, 100, 261, 41))
        self.txt_maSP.setStyleSheet("border-radius: 10px;\n"
"        border: 3px solid #3498db;  /* Viền xanh dương */\n"
"        background-color: #ffffff")
        self.txt_maSP.setObjectName("txt_maSP")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 250, 101, 21))
        self.label_3.setStyleSheet("font: 10pt \"UTM Bell\";\n"
"color: rgb(241, 121, 184);\n"
"")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setStyleSheet(_translate("MainWindow", "color: rgb(149, 106, 214);"))
        self.labelTitle.setText(_translate("MainWindow", "CẬP NHẬT SẢN PHẨM"))
        self.cbo_danhmucSP.setItemText(0, _translate("MainWindow", "Thức ăn"))
        self.cbo_danhmucSP.setItemText(1, _translate("MainWindow", "Đồ chơi"))
        self.cbo_danhmucSP.setItemText(2, _translate("MainWindow", "Phụ kiện"))
        self.label_5.setText(_translate("MainWindow", "DANH MỤC"))
        self.label.setText(_translate("MainWindow", "MÃ SẢN PHẨM"))
        self.lbl_anh.setStyleSheet(_translate("MainWindow", "background-color: rgb(255, 170, 255); border: 2px solid gray;"))
        self.btn_luusp.setText(_translate("MainWindow", "LƯU"))
        self.label_6.setText(_translate("MainWindow", "GIÁ THÀNH"))
        self.label_2.setText(_translate("MainWindow", "TÊN SẢN PHẨM"))
        self.btn_chon_anh.setStyleSheet(_translate("MainWindow", "background-color: rgb(108, 187, 174); color: white; border-radius: 10px;"))
        self.btn_chon_anh.setText(_translate("MainWindow", "Chọn ảnh"))
        self.label_4.setText(_translate("MainWindow", "DANH MỤC"))
        self.label_3.setText(_translate("MainWindow", "SỐ LƯỢNG"))


